### PR TITLE
Update Artwork

### PR DESCRIPTION
**Pull request by JoukjeWillemsen**
I added:
latest versions PNG, JPG & EPS
SVG files
Special editions

### CODE REVIEW

**Comment by J535D165** [comment]
Thanks! The image link in the readme is broken because of the renaming of some files.

**Comment by J535D165** [comment]
Seems to work right now, GitHub is sometimes serving old pages. I will make a couple of edits and merge soon. Thanks!

**Comment by JoukjeWillemsen** [comment]
Hi! Ik heb nieuwe mappen toegevoegd (ElasAdventures (vectorart), Illustrations (tekeningen), LogoASReview, LogoASReviewLAB, SVGicons) met nieuw werk en de readme's geupdated

**Comment by JoukjeWillemsen** [comment]
I added new artwork, added repocards to every folder & extended the readme in the main folder to give an extensive overview of all of the artwork and where to find everything.

**Comment by JoukjeWillemsen** [comment]
I added the json files (Elas jumping with an "training" sign), the quicktour svgs without the text, more Elas adventures & more

**Comment by J535D165** [comment]
THANK YOU SO MUCH!! Great work!!

**Pull request merged**
